stages:
  - test

cypress_tests:
  image: cypress/base:14.16.0
  stage: test
  script:
    - npm install
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/videos
    reports:
      junit:
        - cypress/results/junit-report.xml
